# Cloudflare Pages Configuration for Next.js

name = "resfes"
compatibility_date = "2024-05-02"
compatibility_flags = [ "nodejs_compat" ]

# Pages build directory configuration
[site]
bucket = ".next"
